[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "@chainlink/=lib/foundry-chainlink-toolkit/","@aave/=lib/aave-v3-core","@aave-helpers/=lib/aave-helpers", "aave-v3-origin/=lib/aave-v3-origin/src/", "solidity-utils/=lib/aave-v3-origin/lib/solidity-utils/src/", "aave-v3-origin-tests/=lib/aave-v3-origin/tests/", "aave-address-book/=lib/aave-helpers/lib/aave-address-book/src/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
